from Gempa import *

gempa1 = Gempa('Banten', 1.2)
gempa1.dampak()
print("===============***===============")
gempa2 = Gempa('Palu', 6.1)
gempa2.dampak()
print("===============***===============")
gempa3 = Gempa('Cianjur', 5.6)
gempa3.dampak()
print("===============***===============")
gempa4 = Gempa('Jayapura', 3.3)
gempa4.dampak()
print("===============***===============")
gempa5 = Gempa('Garut', 4.0)
gempa5.dampak()
